### ISSUE TITLE
Camera params

### ISSUE THREAD

**Issue by IQ17** [microsoft/DisentangledFaceGAN#11]
Hi, I don't understand the zoom like operation [here](https://github.com/microsoft/DisentangledFaceGAN/blob/562e95ce4979223e16fbff87fb4b22ff6e1c7071/preprocess/preprocess_utils.py#L201) , what is the value 1.22 in scale?

**Comment by IQ17** [comment]
Is this 1.22 decided by calibrating the scale difference between the real image and rendered one?

**Comment by YuDeng** [comment]
Hi, it is only used for a "zoom-in" of the face region, to reduce the burden of the generator for generating too many additional contents such as the background.

**Comment by YuDeng** [comment]
The scale between rendered image and real ones is already considered in the Preprocess function in line 146.

**Comment by IQ17** [comment]
Why we need this scale = 224/512?  

As far as I understand, this 224 comes from the input shape of the reconstruction network, and thus it limits the resolution of estimated tx ty tz; We use a 512 image to do correction in a sub pixels accuracy;  

But what if I want to prepare a 1024 image, how to adjust and justify this scale ?

Increasing the zoom coefficient from 1.22 to higher to meet 1024 resolution is not good, as in the render phase this will leads to too small fov.

**Comment by IQ17** [comment]
By the way, you mentioned that "reduce the burden of the generator for generating too many additional contents such as the background", did you experienced difficulty in training with background?

**Comment by YuDeng** [comment]
Your understanding is correct. We use a 3D reconstruction network that only receives 224 image as input where the resolution is too low. So for our face generation task which aims to generate face images with 256*256 resolution, we use a 512 image for cancelling scale and tx,ty,tz, then cropped to 256 resolution.

If you want to use higher resolution images, you can simply change the scale 1.22 to some higher value for example 1.22xs, s>1; and change the cropping region from 128 to 128xs; and in the render phase you don't have to change fov because tf.atan(128xs/(1015x1.22xs)) = tf.atan(128/(1015x1.22)).
You only need to change the render resolution. Then everything (cropped image, render image) would looks the same as before except they have higher resolution.

We do not do experiments with more background region. This is only our speculation that introduce more background region maybe harmful.
