### ISSUE TITLE
what difference between W and W+ space ?

### ISSUE THREAD

**Issue by voyager0003** [microsoft/DisentangledFaceGAN#21]
since the [1] paper: "Image2StyleGAN: How to Embed Images Into the StyleGAN Latent Space?" don't have an official implement and in the paper 3.3 just said:
>W+ is a concatenation of 18 different 512-dimensional w vectors

so? W space is 1x18x512，what's the difference?

**Comment by YuDeng** [comment]
The W space vector is of size 1x512, which means the scale and bias parameters for each AdaIN block in StyleGAN are mapped from the same vector in w space. While for W+ space vector, it is of size 18x512, which means that each AdaIN block uses different w vector(1x512) to obtain scale and bias. So the W+ space is of size num_AdaIN_layers x 512. In the case of 1024x1024 image resolution, the number of AdaIN layers is 18, so that W+ space vector is 18x512.
Therefore, W+ space is a larger space compare to W space. Embedding images in W+ space will have better reconstruction results compare to w space embedding, as is shown in Image2StyleGAN paper.

**Comment by voyager0003** [comment]
You're right! I found the shape of w in W space is 1x512 in the repo of Stylegan(https://github.com/NVlabs/stylegan/blob/master/training/networks_stylegan.py)
I should read the stylegan source code more carefully. If do so, I will found althought there is 18 AdaIn Layers in the sythesis network, they share weights.
