### ISSUE TITLE
Reference based generation

### ISSUE THREAD

**Issue by ShawnBIT** [microsoft/DisentangledFaceGAN#5]
Hi, thanks for your great work. I have some trouble when I run the reference-based generation task. First, FaceReconModel.ckpt is not found in the preprocess_data script. Second, how to convert the coefficient extracted in lamda space to the latent code in z space. Look forward to your reply.

**Comment by YuDeng** [comment]
Hi, to run data preprocessing, you should first follow the instruction in the training preparation section to download and extract FaceReconModel.ckpt and put it in the corresponding folder. 
And for the second question, there is no need to convert lambda space coefficients to z space because our generator takes lambda space vectors as input.

**Comment by YuDeng** [comment]
I find that there exists a name error.  The name of the pre-trained model should be "FaceReconModel" instead of "FaceReconModel.ckpt". I have fixed this error in the latest update. You can try if it runs correctly now. Sorry for the inconvenience.
